# Generated by Django 5.0.7 on 2024-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/cat/default2.png', upload_to='catimages'),
        ),
    ]
